import type { Country, Difficulty } from "./index.js";

/** Curated list with EN/RU names and difficulty tier for flag guessing. */
export const COUNTRIES: Country[] = [
  // easy — widely recognizable
  { code: "US", en: "United States", ru: "США", difficulty: "easy" },
  { code: "GB", en: "United Kingdom", ru: "Великобритания", difficulty: "easy" },
  { code: "FR", en: "France", ru: "Франция", difficulty: "easy" },
  { code: "DE", en: "Germany", ru: "Германия", difficulty: "easy" },
  { code: "IT", en: "Italy", ru: "Италия", difficulty: "easy" },
  { code: "ES", en: "Spain", ru: "Испания", difficulty: "easy" },
  { code: "JP", en: "Japan", ru: "Япония", difficulty: "easy" },
  { code: "CN", en: "China", ru: "Китай", difficulty: "easy" },
  { code: "BR", en: "Brazil", ru: "Бразилия", difficulty: "easy" },
  { code: "CA", en: "Canada", ru: "Канада", difficulty: "easy" },
  { code: "AU", en: "Australia", ru: "Австралия", difficulty: "easy" },
  { code: "RU", en: "Russia", ru: "Россия", difficulty: "easy" },
  { code: "IN", en: "India", ru: "Индия", difficulty: "easy" },
  { code: "MX", en: "Mexico", ru: "Мексика", difficulty: "easy" },
  { code: "KR", en: "South Korea", ru: "Южная Корея", difficulty: "easy" },
  { code: "TR", en: "Turkey", ru: "Турция", difficulty: "easy" },
  { code: "NL", en: "Netherlands", ru: "Нидерланды", difficulty: "easy" },
  { code: "SE", en: "Sweden", ru: "Швеция", difficulty: "easy" },
  { code: "CH", en: "Switzerland", ru: "Швейцария", difficulty: "easy" },
  { code: "PL", en: "Poland", ru: "Польша", difficulty: "easy" },
  { code: "AR", en: "Argentina", ru: "Аргентина", difficulty: "easy" },
  { code: "ZA", en: "South Africa", ru: "ЮАР", difficulty: "easy" },
  { code: "EG", en: "Egypt", ru: "Египет", difficulty: "easy" },
  { code: "GR", en: "Greece", ru: "Греция", difficulty: "easy" },
  { code: "PT", en: "Portugal", ru: "Португалия", difficulty: "easy" },
  { code: "IE", en: "Ireland", ru: "Ирландия", difficulty: "easy" },
  { code: "NO", en: "Norway", ru: "Норвегия", difficulty: "easy" },
  { code: "FI", en: "Finland", ru: "Финляндия", difficulty: "easy" },
  { code: "DK", en: "Denmark", ru: "Дания", difficulty: "easy" },
  { code: "AT", en: "Austria", ru: "Австрия", difficulty: "easy" },
  { code: "BE", en: "Belgium", ru: "Бельгия", difficulty: "easy" },
  { code: "NZ", en: "New Zealand", ru: "Новая Зеландия", difficulty: "easy" },
  { code: "IL", en: "Israel", ru: "Израиль", difficulty: "easy" },
  { code: "SA", en: "Saudi Arabia", ru: "Саудовская Аравия", difficulty: "easy" },
  { code: "TH", en: "Thailand", ru: "Таиланд", difficulty: "easy" },
  { code: "UA", en: "Ukraine", ru: "Украина", difficulty: "easy" },

  // medium
  { code: "CZ", en: "Czechia", ru: "Чехия", difficulty: "medium" },
  { code: "HU", en: "Hungary", ru: "Венгрия", difficulty: "medium" },
  { code: "RO", en: "Romania", ru: "Румыния", difficulty: "medium" },
  { code: "BG", en: "Bulgaria", ru: "Болгария", difficulty: "medium" },
  { code: "HR", en: "Croatia", ru: "Хорватия", difficulty: "medium" },
  { code: "RS", en: "Serbia", ru: "Сербия", difficulty: "medium" },
  { code: "SK", en: "Slovakia", ru: "Словакия", difficulty: "medium" },
  { code: "SI", en: "Slovenia", ru: "Словения", difficulty: "medium" },
  { code: "LT", en: "Lithuania", ru: "Литва", difficulty: "medium" },
  { code: "LV", en: "Latvia", ru: "Латвия", difficulty: "medium" },
  { code: "EE", en: "Estonia", ru: "Эстония", difficulty: "medium" },
  { code: "IS", en: "Iceland", ru: "Исландия", difficulty: "medium" },
  { code: "LU", en: "Luxembourg", ru: "Люксембург", difficulty: "medium" },
  { code: "MT", en: "Malta", ru: "Мальта", difficulty: "medium" },
  { code: "CY", en: "Cyprus", ru: "Кипр", difficulty: "medium" },
  { code: "BY", en: "Belarus", ru: "Беларусь", difficulty: "medium" },
  { code: "MD", en: "Moldova", ru: "Молдова", difficulty: "medium" },
  { code: "GE", en: "Georgia", ru: "Грузия", difficulty: "medium" },
  { code: "AM", en: "Armenia", ru: "Армения", difficulty: "medium" },
  { code: "AZ", en: "Azerbaijan", ru: "Азербайджан", difficulty: "medium" },
  { code: "KZ", en: "Kazakhstan", ru: "Казахстан", difficulty: "medium" },
  { code: "UZ", en: "Uzbekistan", ru: "Узбекистан", difficulty: "medium" },
  { code: "PK", en: "Pakistan", ru: "Пакистан", difficulty: "medium" },
  { code: "BD", en: "Bangladesh", ru: "Бангладеш", difficulty: "medium" },
  { code: "VN", en: "Vietnam", ru: "Вьетнам", difficulty: "medium" },
  { code: "PH", en: "Philippines", ru: "Филиппины", difficulty: "medium" },
  { code: "ID", en: "Indonesia", ru: "Индонезия", difficulty: "medium" },
  { code: "MY", en: "Malaysia", ru: "Малайзия", difficulty: "medium" },
  { code: "SG", en: "Singapore", ru: "Сингапур", difficulty: "medium" },
  { code: "CL", en: "Chile", ru: "Чили", difficulty: "medium" },
  { code: "CO", en: "Colombia", ru: "Колумбия", difficulty: "medium" },
  { code: "PE", en: "Peru", ru: "Перу", difficulty: "medium" },
  { code: "VE", en: "Venezuela", ru: "Венесуэла", difficulty: "medium" },
  { code: "EC", en: "Ecuador", ru: "Эквадор", difficulty: "medium" },
  { code: "UY", en: "Uruguay", ru: "Уругвай", difficulty: "medium" },
  { code: "BO", en: "Bolivia", ru: "Боливия", difficulty: "medium" },
  { code: "PY", en: "Paraguay", ru: "Парагвай", difficulty: "medium" },
  { code: "NG", en: "Nigeria", ru: "Нигерия", difficulty: "medium" },
  { code: "KE", en: "Kenya", ru: "Кения", difficulty: "medium" },
  { code: "ET", en: "Ethiopia", ru: "Эфиопия", difficulty: "medium" },
  { code: "MA", en: "Morocco", ru: "Марокко", difficulty: "medium" },
  { code: "DZ", en: "Algeria", ru: "Алжир", difficulty: "medium" },
  { code: "TN", en: "Tunisia", ru: "Тунис", difficulty: "medium" },
  { code: "GH", en: "Ghana", ru: "Гана", difficulty: "medium" },
  { code: "AE", en: "United Arab Emirates", ru: "ОАЭ", difficulty: "medium" },
  { code: "QA", en: "Qatar", ru: "Катар", difficulty: "medium" },
  { code: "KW", en: "Kuwait", ru: "Кувейт", difficulty: "medium" },
  { code: "OM", en: "Oman", ru: "Оман", difficulty: "medium" },
  { code: "JO", en: "Jordan", ru: "Иордания", difficulty: "medium" },
  { code: "LB", en: "Lebanon", ru: "Ливан", difficulty: "medium" },
  { code: "IR", en: "Iran", ru: "Иран", difficulty: "medium" },
  { code: "IQ", en: "Iraq", ru: "Ирак", difficulty: "medium" },
  { code: "LK", en: "Sri Lanka", ru: "Шри-Ланка", difficulty: "medium" },
  { code: "NP", en: "Nepal", ru: "Непал", difficulty: "medium" },
  { code: "MM", en: "Myanmar", ru: "Мьянма", difficulty: "medium" },
  { code: "KH", en: "Cambodia", ru: "Камбоджа", difficulty: "medium" },
  { code: "LA", en: "Laos", ru: "Лаос", difficulty: "medium" },
  { code: "MN", en: "Mongolia", ru: "Монголия", difficulty: "medium" },
  { code: "CU", en: "Cuba", ru: "Куба", difficulty: "medium" },
  { code: "DO", en: "Dominican Republic", ru: "Доминикана", difficulty: "medium" },
  { code: "CR", en: "Costa Rica", ru: "Коста-Рика", difficulty: "medium" },
  { code: "PA", en: "Panama", ru: "Панама", difficulty: "medium" },
  { code: "GT", en: "Guatemala", ru: "Гватемала", difficulty: "medium" },
  { code: "HN", en: "Honduras", ru: "Гондурас", difficulty: "medium" },
  { code: "SV", en: "El Salvador", ru: "Сальвадор", difficulty: "medium" },
  { code: "NI", en: "Nicaragua", ru: "Никарагуа", difficulty: "medium" },

  // hard — less familiar flags
  { code: "TJ", en: "Tajikistan", ru: "Таджикистан", difficulty: "hard" },
  { code: "KG", en: "Kyrgyzstan", ru: "Кыргызстан", difficulty: "hard" },
  { code: "TM", en: "Turkmenistan", ru: "Туркменистан", difficulty: "hard" },
  { code: "BT", en: "Bhutan", ru: "Бутан", difficulty: "hard" },
  { code: "BN", en: "Brunei", ru: "Бруней", difficulty: "hard" },
  { code: "TL", en: "Timor-Leste", ru: "Восточный Тимор", difficulty: "hard" },
  { code: "FJ", en: "Fiji", ru: "Фиджи", difficulty: "hard" },
  { code: "PG", en: "Papua New Guinea", ru: "Папуа — Новая Гвинея", difficulty: "hard" },
  { code: "SB", en: "Solomon Islands", ru: "Соломоновы Острова", difficulty: "hard" },
  { code: "VU", en: "Vanuatu", ru: "Вануату", difficulty: "hard" },
  { code: "WS", en: "Samoa", ru: "Самоа", difficulty: "hard" },
  { code: "TO", en: "Tonga", ru: "Тонга", difficulty: "hard" },
  { code: "KI", en: "Kiribati", ru: "Кирибати", difficulty: "hard" },
  { code: "TV", en: "Tuvalu", ru: "Тувалу", difficulty: "hard" },
  { code: "NR", en: "Nauru", ru: "Науру", difficulty: "hard" },
  { code: "PW", en: "Palau", ru: "Палау", difficulty: "hard" },
  { code: "FM", en: "Micronesia", ru: "Микронезия", difficulty: "hard" },
  { code: "MH", en: "Marshall Islands", ru: "Маршалловы Острова", difficulty: "hard" },
  { code: "MZ", en: "Mozambique", ru: "Мозамбик", difficulty: "hard" },
  { code: "AO", en: "Angola", ru: "Ангола", difficulty: "hard" },
  { code: "ZM", en: "Zambia", ru: "Замбия", difficulty: "hard" },
  { code: "ZW", en: "Zimbabwe", ru: "Зимбабве", difficulty: "hard" },
  { code: "BW", en: "Botswana", ru: "Ботсвана", difficulty: "hard" },
  { code: "NA", en: "Namibia", ru: "Намибия", difficulty: "hard" },
  { code: "MG", en: "Madagascar", ru: "Мадагаскар", difficulty: "hard" },
  { code: "MU", en: "Mauritius", ru: "Маврикий", difficulty: "hard" },
  { code: "SC", en: "Seychelles", ru: "Сейшелы", difficulty: "hard" },
  { code: "RW", en: "Rwanda", ru: "Руанда", difficulty: "hard" },
  { code: "BI", en: "Burundi", ru: "Бурунди", difficulty: "hard" },
  { code: "UG", en: "Uganda", ru: "Уганда", difficulty: "hard" },
  { code: "TZ", en: "Tanzania", ru: "Танзания", difficulty: "hard" },
  { code: "SN", en: "Senegal", ru: "Сенегал", difficulty: "hard" },
  { code: "CI", en: "Côte d'Ivoire", ru: "Кот-д’Ивуар", difficulty: "hard" },
  { code: "CM", en: "Cameroon", ru: "Камерун", difficulty: "hard" },
  { code: "GA", en: "Gabon", ru: "Габон", difficulty: "hard" },
  { code: "CG", en: "Republic of the Congo", ru: "Республика Конго", difficulty: "hard" },
  { code: "CD", en: "DR Congo", ru: "ДР Конго", difficulty: "hard" },
  { code: "BF", en: "Burkina Faso", ru: "Буркина-Фасо", difficulty: "hard" },
  { code: "ML", en: "Mali", ru: "Мали", difficulty: "hard" },
  { code: "NE", en: "Niger", ru: "Нигер", difficulty: "hard" },
  { code: "TD", en: "Chad", ru: "Чад", difficulty: "hard" },
  { code: "SD", en: "Sudan", ru: "Судан", difficulty: "hard" },
  { code: "SS", en: "South Sudan", ru: "Южный Судан", difficulty: "hard" },
  { code: "ER", en: "Eritrea", ru: "Эритрея", difficulty: "hard" },
  { code: "DJ", en: "Djibouti", ru: "Джибути", difficulty: "hard" },
  { code: "SO", en: "Somalia", ru: "Сомали", difficulty: "hard" },
  { code: "LY", en: "Libya", ru: "Ливия", difficulty: "hard" },
  { code: "MR", en: "Mauritania", ru: "Мавритания", difficulty: "hard" },
  { code: "GM", en: "Gambia", ru: "Гамбия", difficulty: "hard" },
  { code: "GW", en: "Guinea-Bissau", ru: "Гвинея-Бисау", difficulty: "hard" },
  { code: "GN", en: "Guinea", ru: "Гвинея", difficulty: "hard" },
  { code: "SL", en: "Sierra Leone", ru: "Сьерра-Леоне", difficulty: "hard" },
  { code: "LR", en: "Liberia", ru: "Либерия", difficulty: "hard" },
  { code: "TG", en: "Togo", ru: "Того", difficulty: "hard" },
  { code: "BJ", en: "Benin", ru: "Бенин", difficulty: "hard" },
  { code: "CV", en: "Cape Verde", ru: "Кабо-Верде", difficulty: "hard" },
  { code: "ST", en: "São Tomé and Príncipe", ru: "Сан-Томе и Принсипи", difficulty: "hard" },
  { code: "GQ", en: "Equatorial Guinea", ru: "Экваториальная Гвинея", difficulty: "hard" },
  { code: "CF", en: "Central African Republic", ru: "ЦАР", difficulty: "hard" },
  { code: "LS", en: "Lesotho", ru: "Лесото", difficulty: "hard" },
  { code: "SZ", en: "Eswatini", ru: "Эсватини", difficulty: "hard" },
  { code: "MW", en: "Malawi", ru: "Малави", difficulty: "hard" },
  { code: "KM", en: "Comoros", ru: "Коморы", difficulty: "hard" },
  { code: "AL", en: "Albania", ru: "Албания", difficulty: "hard" },
  { code: "MK", en: "North Macedonia", ru: "Северная Македония", difficulty: "hard" },
  { code: "ME", en: "Montenegro", ru: "Черногория", difficulty: "hard" },
  { code: "BA", en: "Bosnia and Herzegovina", ru: "Босния и Герцеговина", difficulty: "hard" },
  { code: "XK", en: "Kosovo", ru: "Косово", difficulty: "hard" },
  { code: "AD", en: "Andorra", ru: "Андорра", difficulty: "hard" },
  { code: "MC", en: "Monaco", ru: "Монако", difficulty: "hard" },
  { code: "SM", en: "San Marino", ru: "Сан-Марино", difficulty: "hard" },
  { code: "LI", en: "Liechtenstein", ru: "Лихтенштейн", difficulty: "hard" },
  { code: "VA", en: "Vatican City", ru: "Ватикан", difficulty: "hard" },
  { code: "BB", en: "Barbados", ru: "Барбадос", difficulty: "hard" },
  { code: "TT", en: "Trinidad and Tobago", ru: "Тринидад и Тобаго", difficulty: "hard" },
  { code: "JM", en: "Jamaica", ru: "Ямайка", difficulty: "hard" },
  { code: "HT", en: "Haiti", ru: "Гаити", difficulty: "hard" },
  { code: "BZ", en: "Belize", ru: "Белиз", difficulty: "hard" },
  { code: "GY", en: "Guyana", ru: "Гайана", difficulty: "hard" },
  { code: "SR", en: "Suriname", ru: "Суринам", difficulty: "hard" },
  { code: "BS", en: "Bahamas", ru: "Багамы", difficulty: "hard" },
  { code: "AG", en: "Antigua and Barbuda", ru: "Антигуа и Барбуда", difficulty: "hard" },
  { code: "DM", en: "Dominica", ru: "Доминика", difficulty: "hard" },
  { code: "GD", en: "Grenada", ru: "Гренада", difficulty: "hard" },
  { code: "LC", en: "Saint Lucia", ru: "Сент-Люсия", difficulty: "hard" },
  { code: "VC", en: "Saint Vincent and the Grenadines", ru: "Сент-Винсент и Гренадины", difficulty: "hard" },
  { code: "KN", en: "Saint Kitts and Nevis", ru: "Сент-Китс и Невис", difficulty: "hard" },
];

const byCode = new Map(COUNTRIES.map((c) => [c.code, c]));

export function getCountry(code: string): Country | undefined {
  return byCode.get(code);
}

export function poolForDifficulty(difficulty: Difficulty): Country[] {
  if (difficulty === "easy") return COUNTRIES.filter((c) => c.difficulty === "easy");
  if (difficulty === "medium")
    return COUNTRIES.filter((c) => c.difficulty === "easy" || c.difficulty === "medium");
  return COUNTRIES;
}

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
